### PR TITLE
Fix workspace for local runs

### PR DESCRIPTION
**Pull request by JonZeolla**
# Contributor Comments
This fixes local runs of the `goat`, which have been broken since #14

## Pull Request Checklist
Thank you for submitting a contribution to `goat`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:
- [X] Rebase your branch against the latest commit of the target branch, which likely should be `main`
- [X] If there is an issue associated with your Pull Request, align your PR title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Review by jimmio — COMMENTED** [review]
I'm consistently getting a timeout after about 5min on `pipenv run invoke goat`. Increasing the [timeout to 1000](https://github.com/SeisoLLC/goat/blob/2edec7701d87a69cebc34d3a3c78b3018c84713f/tasks.py#L152) and then rebuilding with `pipenv run invoke build` did not make a difference. Am I missing something?
```
{"timestamp": "2021-03-08 14:29:09,176", "namespace": "seiso.goat", "loglevel": "INFO", "message": "Baaaaaaaaaaah! (Running the goat)"}
{"timestamp": "2021-03-08 14:30:32,449", "namespace": "seiso.goat", "loglevel": "INFO", "message": "Linting tests passed"}
{"timestamp": "2021-03-08 14:35:42,967", "namespace": "seiso.goat", "loglevel": "ERROR", "message": "Received a baaaaaaaaah-d status code from docker (1); additional details: 2021-03-08T19:35:42.296Z        FATAL   error in image scan: failed analysis: analyze error: timeout: context deadline exceeded"}
```

**Comment by pb-seiso** [comment]
> I'm consistently getting a timeout after about 5min on `pipenv run invoke goat`. Increasing the [timeout to 1000](https://github.com/SeisoLLC/goat/blob/2edec7701d87a69cebc34d3a3c78b3018c84713f/tasks.py#L152) and then rebuilding with `pipenv run invoke build` did not make a difference. Am I missing something?
> 
> ```
> {"timestamp": "2021-03-08 14:29:09,176", "namespace": "seiso.goat", "loglevel": "INFO", "message": "Baaaaaaaaaaah! (Running the goat)"}
> {"timestamp": "2021-03-08 14:30:32,449", "namespace": "seiso.goat", "loglevel": "INFO", "message": "Linting tests passed"}
> {"timestamp": "2021-03-08 14:35:42,967", "namespace": "seiso.goat", "loglevel": "ERROR", "message": "Received a baaaaaaaaah-d status code from docker (1); additional details: 2021-03-08T19:35:42.296Z        FATAL   error in image scan: failed analysis: analyze error: timeout: context deadline exceeded"}
> ```

I get the same errors as Jim both when running locally and with `invoke goat`.

**Comment by JonZeolla** [comment]
@pb-seiso and @jimmio this is a known issue on the backlog [here](https://www.wrike.com/open.htm?id=643559877), I don't know what's going on there yet.  Chipping away at that one would be useful; it has also hit Tyler in his testing of the `goat`.  I think the issue has to do with the `trivy` scan pointing to the full image on disk and I highly expect that can be improved.

This is working in CI? ¯\_(ツ)_/¯

**Comment by JonZeolla** [comment]
@pb-seiso can you describe what you mean by "running locally"?  Are you doing:
```bash
pipenv run invoke build && docker run -e RUN_LOCAL=true -v $(pwd):/goat/ -w /goat/ seiso/goat:latest
```

Because that works fine for me; I think the issues are unrelated.

**Comment by pb-seiso** [comment]
> @pb-seiso can you describe what you mean by "running locally"? Are you doing:
> 
> ```shell
> pipenv run invoke build && docker run -e RUN_LOCAL=true -v $(pwd):/goat/ -w /goat/ seiso/goat:latest
> ```
> 
> Because that works fine for me; I think the issues are unrelated.

@JonZeolla By locally I mean running `pipenv run invoke goat` as specified by the README. Your command above works fine for me.

It looks like the error is generated from `trivy` when running `run_security_tests` - see [here](https://github.com/aquasecurity/trivy/issues/802). The [accepted fix](https://github.com/aquasecurity/trivy/pull/842) was to increase Trivy's default timeout value to 5 minutes but that isn't working for us here. I hardcoded it to 10 minutes (`tasks.py:95`) and still got the same error:

`"--quiet image --exit-code 0 --timeout 10m0s --severity "`

Might be worth opening another ticket with Aqua.

**Comment by JonZeolla** [comment]
@pb-seiso I was confused because you said "running locally and with `invoke goat`".  Are you referring to attempting `pipenv run invoke goat` and `invoke goat`?

**Comment by JonZeolla** [comment]
@pb-seiso if you're already troubleshooting that issue can you self-assign it and run with working with the Aqua team?  I think we can separate that discussion from this PR

**Comment by pb-seiso** [comment]
> @pb-seiso I was confused because you said "running locally and with `invoke goat`". Are you referring to attempting `pipenv run invoke goat` and `invoke goat`?

Yes, I used "locally" as a shorthand consistent with the language in the [README](https://github.com/SeisoLLC/goat#running-the-goat-locally).

> @pb-seiso if you're already troubleshooting that issue can you self-assign it and run with working with the Aqua team? I think we can separate that discussion from this PR

@JonZeolla I don't have permission to open an issue. Can you either provide permission or open it and I can fill in the details?

image

**Comment by JonZeolla** [comment]
@pb-seiso Perfect, thanks for the clarification.

Let's sync up on the issue.  I was expecting you would self-assign the existing task related to this, and potentially create a new issue against trivy, if it's warranted.  Did you click the task link I provided [here](https://github.com/SeisoLLC/goat/pull/17#issuecomment-793185992)?

**Review by pb-seiso — APPROVED** [review]
LGTM!

**Comment by pb-seiso** [comment]
> @pb-seiso Perfect, thanks for the clarification.
> 
> Let's sync up on the issue. I was expecting you would self-assign the existing task related to this, and potentially create a new issue against trivy, if it's warranted. Did you click the task link I provided [here](https://github.com/SeisoLLC/goat/pull/17#issuecomment-793185992)?

Sure, I'll take that task and follow up with Aqua.

**Pull request merged**
